---
root: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    impliedStrict: true
  ecmaVersion: 2022
  lib:
    - ES2022
  sourceType: module

plugins:
  - "@typescript-eslint"
  - nova

env:
  es2022: true
  jest: true
  node: true
  nova/nova: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier # provided by eslint-config-prettier

rules:
  "@typescript-eslint/naming-convention": warn
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/semi": warn
  curly: warn
  eqeqeq: warn
  no-throw-literal: warn
  semi: off
