repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: \.nova.*/
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.10.0
    hooks:
      - id: eslint
        types: [file]
        files: \.[jt]s$
        args: [--fix]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@4.3.0"
          - "@typescript-eslint/parser@4.3.0"
          - eslint-config-prettier@6.12.0
          - eslint-plugin-prettier@3.1.4

  - repo: https://github.com/prettier/prettier
    rev: "2.1.2"
    hooks:
      - id: prettier
